// using ES6 modules
import mitt from 'mitt'

const globalEventBus = mitt()

export default globalEventBus

export const GlobalEvents = {
  ACTION_PLAY_START: 'ACTION_PLAY_START',
  ACTION_TOGGLE_PLAY: 'ACTION_TOGGLE_PLAY',
  ACTION_PREV: 'ACTION_PREV',
  ACTION_NEXT: 'ACTION_NEXT',
  ACTION_PLAY_ENDED: 'ACTION_PLAY_ENDED',
  ACTION_CHANGE_CURRENT_TIME: 'ACTION_CHANGE_CURRENT_TIME',
  ACTION_CHANGE_SPEED: 'ACTION_CHANGE_SPEED',
  ACTION_CHANGE_VOLUME: 'ACTION_CHANGE_VOLUME',
  ACTION_LOCATE_FILE: 'ACTION_LOCATE_FILE',
  ACTION_REFRESH_FILESYSTEM: 'ACTION_REFRESH_FILESYSTEM',
  ACTION_ADD_PLAYLIST: 'ACTION_ADD_PLAYLIST',
  ACTION_DOWNLOAD_FILE: 'ACTION_DOWNLOAD_FILE',
  ACTION_ADD_LIST_PLAY_NEXT: 'ACTION_ADD_LIST_PLAY_NEXT',
}
