/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoRatioBox: typeof import('./src/components/CommonUI/AutoRatioBox.vue')['default']
    CoverDisplay: typeof import('./src/components/MusicPlayer/CoverDisplay.vue')['default']
    CoverMini: typeof import('./src/components/MusicPlayer/CoverMini.vue')['default']
    DialogImageCropper: typeof import('./src/components/CommonUI/DialogImageCropper.vue')['default']
    DialogTextEdit: typeof import('./src/components/CommonUI/DialogTextEdit.vue')['default']
    DropZone: typeof import('./src/components/CommonUI/DropZone.vue')['default']
    FileChooser: typeof import('./src/components/CommonUI/FileChooser.vue')['default']
    FileDrop: typeof import('./src/components/CommonUI/FileDrop.vue')['default']
    FileManager: typeof import('./src/components/FileManager/FileManager.vue')['default']
    MusicControl: typeof import('./src/components/MusicPlayer/MusicControl.vue')['default']
    MusicDetail: typeof import('./src/components/MusicPlayer/MusicDetail.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    PlayerCore: typeof import('./src/components/MusicPlayer/PlayerCore.vue')['default']
    PlayerCoreV2: typeof import('./src/components/MusicPlayer/PlayerCoreV2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeekBar: typeof import('./src/components/CommonUI/SeekBar.vue')['default']
    TkSeekBar: typeof import('./src/components/CommonUI/TkSeekBar.vue')['default']
    ViewPortWindow: typeof import('./src/components/CommonUI/ViewPortWindow/index.vue')['default']
    VueMonaco: typeof import('./src/components/CommonUI/VueMonaco.vue')['default']
  }
}
