/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoRatioBox: typeof import('./src/components/CommonUI/AutoRatioBox.vue')['default']
    CoverDisplay: typeof import('./src/components/Apps/MusicPlayer/CoverDisplay.vue')['default']
    CoverMini: typeof import('./src/components/Apps/MusicPlayer/CoverMini.vue')['default']
    Desktop: typeof import('./src/components/OS/DesktopWindowManager/index.vue')['default']
    DesktopContent: typeof import('./src/components/OS/DesktopWindowManager/DesktopContent.vue')['default']
    DesktopWallpaper: typeof import('./src/components/OS/DesktopWindowManager/DesktopWallpaper.vue')['default']
    DesktopWindowManager: typeof import('./src/components/OS/DesktopWindowManager/index.vue')['default']
    DialogImageCropper: typeof import('./src/components/CommonUI/DialogImageCropper.vue')['default']
    DialogTextEdit: typeof import('./src/components/CommonUI/DialogTextEdit.vue')['default']
    DropZone: typeof import('./src/components/CommonUI/DropZone.vue')['default']
    FileChooser: typeof import('./src/components/CommonUI/FileChooser.vue')['default']
    FileDrop: typeof import('./src/components/CommonUI/FileDrop.vue')['default']
    FileManager: typeof import('./src/components/Apps/FileManager/index.vue')['default']
    IframeBrowser: typeof import('./src/components/Apps/IframeBrowser/index.vue')['default']
    MusicControl: typeof import('./src/components/Apps/MusicPlayer/MusicControl.vue')['default']
    MusicDetail: typeof import('./src/components/Apps/MusicPlayer/MusicDetail.vue')['default']
    MusicPlayer: typeof import('./src/components/Apps/MusicPlayer/index.vue')['default']
    MusicPlaylist: typeof import('./src/components/Apps/MusicPlayer/MusicPlaylist/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    PlayerCore: typeof import('./src/components/Apps/MusicPlayer/PlayerCore.vue')['default']
    PlayerCoreV2: typeof import('./src/components/Apps/MusicPlayer/PlayerCoreV2.vue')['default']
    PlaylistItem: typeof import('./src/components/Apps/MusicPlayer/MusicPlaylist/PlaylistItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeekBar: typeof import('./src/components/CommonUI/SeekBar.vue')['default']
    SettingsApp: typeof import('./src/components/Apps/SettingsApp/index.vue')['default']
    StartMenu: typeof import('./src/components/OS/StartMenu/index.vue')['default']
    StartMenuItem: typeof import('./src/components/OS/StartMenu/StartMenuItem.vue')['default']
    TaskBar: typeof import('./src/components/OS/TaskBar/index.vue')['default']
    TkSeekBar: typeof import('./src/components/CommonUI/TkSeekBar.vue')['default']
    TrayClock: typeof import('./src/components/OS/TaskBar/TrayClock.vue')['default']
    ViewPortWindow: typeof import('./src/components/CommonUI/ViewPortWindow/index.vue')['default']
    VueMonaco: typeof import('./src/components/CommonUI/VueMonaco.vue')['default']
    Window: typeof import('./src/components/OS/Window/index.vue')['default']
  }
}
